name: comp3050-dev

services:
  server:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/main/server
    command: bash -c "javac *.java && java Server & nginx -g 'daemon off;'"
    ports:
      - "80:80"
    expose:
      - "8000"
    volumes:
      - ..:/workspace
