name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test using maven
        run: mvn test

      - name: Compile server
        run: mvn -q compile

      - name: Build production Docker image
        run: docker build -t game-server:latest .

  scan-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan source code with Semgrep
        run: |
          pip3 install semgrep
          semgrep --config .semgrep.yml --config auto --error src/main/

  scan-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t game-server:latest .

      - name: Install Trivy 
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/refs/tags/v0.69.3/contrib/install.sh | sh -s -- -b /usr/local/bin v0.69.3
      - name: Run Trivy Scan 
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 game-server:latest
